apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tdemotdt
  labels:
    apps.tanzu.vmware.com/workload-type: web
    foo: bar
    app.kubernetes.io/component: run
    carto.run/workload-name: tdemotdt
spec:
  template:
    metadata:
      annotations:
        boot.spring.io/version: 2.6.2
        conventions.apps.tanzu.vmware.com/applied-conventions: |-
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"apps.tanzu.vmware.com/workload-type":"web"},"name":"tdemotdt","namespace":"default"},"spec":{"params":[{"name":"gitops_repository","value":"ssh://git@github.com/tfynes-pivotal/tap-deliverables"},{"name":"gitops_ssh_secret","value":"git-ssh"}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/tfynes-pivotal/tdemo1"}}},"status":{"supplyChainRef":{}}}
      labels:
        app.kubernetes.io/component: run
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: tdemotdt
        conventions.apps.tanzu.vmware.com/framework: spring-boot
        foo: bar
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.health.probes.enabled="true" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: index.docker.io/fynesy/tdemotdt-default@sha256:9ed6fe43e3f49b52cb267fd9589931b4af3f6c24dd19f7e58cd6bd6567600004
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

